export type { LocaleId, LocaleStrings, OrdinalGender } from './i18n/types.js'
export { getDefaultLocale, setDefaultLocale } from './defaults.js'
export { intcomma } from './numbers/intcomma.js'
export type { IntcommaOptions } from './numbers/intcomma.js'
export { intword } from './numbers/intword.js'
export type { IntwordOptions } from './numbers/intword.js'
export { ordinal } from './numbers/ordinal.js'
export type { OrdinalOptions } from './numbers/ordinal.js'
